# Generated by Django 3.1.4 on 2021-02-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefilemodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
